config/routes.rb
Rails.application.routes.draw do

  root 'todo_lists#index'

  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"

  resources :sessions, only: [:new, :create, :destroy]

   resources :todo_lists do
      resources :todo_items
    end

end

app/models/todo_list_item.rb
class TodoItem < ActiveRecord::Base
	belongs_to :todo_list
end

app/controllers/todo_list_items_controller.rb
class TodoListItemsController < ApplicationController
  before_action :set_todo_list_item, only: [:show, :edit, :update, :destroy]

  # GET /todo_list_items
  # GET /todo_list_items.json
  def index
    @todo_list_items = TodoListItem.all
  end

  # GET /todo_list_items/1
  # GET /todo_list_items/1.json
  def show
  end

  # GET /todo_list_items/new
  def new
    @todo_list_item = TodoListItem.new
  end

  # GET /todo_list_items/1/edit
  def edit
  end

  # POST /todo_list_items
  # POST /todo_list_items.json
  def create
    @todo_list_item = TodoListItem.new(todo_list_item_params)

    respond_to do |format|
      if @todo_list_item.save
        format.html { redirect_to @todo_list_item, notice: 'Todo list item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list_item }
      else
        format.html { render :new }
        format.json { render json: @todo_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_list_items/1
  # PATCH/PUT /todo_list_items/1.json
  def update
    respond_to do |format|
      if @todo_list_item.update(todo_list_item_params)
        format.html { redirect_to @todo_list_item, notice: 'Todo list item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list_item }
      else
        format.html { render :edit }
        format.json { render json: @todo_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_list_items/1
  # DELETE /todo_list_items/1.json
  def destroy
    @todo_list_item.destroy
    respond_to do |format|
      format.html { redirect_to todo_list_items_url, notice: 'Todo list item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list_item
      @todo_list_item = TodoListItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_item_params
      params.require(:todo_list_item).permit(:due_date, :title, :description, :completed)
    end
end

app/helpers/todo_list_items_helper.rb
module TodoListItemsHelper
end

app/views/todo_list_items/_form.html.erb
<%= form_for(@todo_list_item) do |f| %>
  <% if @todo_list_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list_item.errors.count, "error") %> prohibited this todo_list_item from being saved:</h2>

      <ul>
      <% @todo_list_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_list_items/edit.html.erb
<h1>Editing Todo List Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list_item %> |
<%= link_to 'Back', todo_list_items_path %>

app/views/todo_list_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todo List Items</h1>

<table>
  <thead>
    <tr>
      <th>Due date</th>
      <th>Title</th>
      <th>Description</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_list_items.each do |todo_list_item| %>
      <tr>
        <td><%= todo_list_item.due_date %></td>
        <td><%= todo_list_item.title %></td>
        <td><%= todo_list_item.description %></td>
        <td><%= todo_list_item.completed %></td>
        <td><%= link_to 'Show', todo_list_item %></td>
        <td><%= link_to 'Edit', edit_todo_list_item_path(todo_list_item) %></td>
        <td><%= link_to 'Destroy', todo_list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo list item', new_todo_list_item_path %>

app/views/todo_list_items/new.html.erb
<h1>New Todo List Item</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_list_items_path %>

app/views/todo_list_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Due date:</strong>
  <%= @todo_list_item.due_date %>
</p>

<p>
  <strong>Title:</strong>
  <%= @todo_list_item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_list_item.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo_list_item.completed %>
</p>

<%= link_to 'Edit', edit_todo_list_item_path(@todo_list_item) %> |
<%= link_to 'Back', todo_list_items_path %>